language: node_js
node_js:
  - "node"

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - yarn
  - cp tests/config/example.js tests/config/production.js
  - sed -i -e "s|your:instance:locator|$CHATKIT_INSTANCE_LOCATOR|g" tests/config/production.js
  - sed -i -e "s|your:key|$CHATKIT_INSTANCE_KEY|g" tests/config/production.js
  - sed -i -e "s|https://token.provider.url|$CHATKIT_TOKEN_PROVIDER_URL|g" tests/config/production.js

script:
  - yarn lint:build:test
